jwt:
  signerKey: "d6ad4b004a0e52c86afdc7f283ed735f906736c05d8be178606f62efaabe11007af47f17e1b4c335f51cf52887d6abced19fb16903dadcad6106cda1474bc26a"
kafka:
  borrow: "borroww"
  return: "returnn"
server:
  port: 8081
  servlet:
    context-path: /book
spring:
  application:
    name: book-service
  datasource:
    url: "jdbc:mysql://localhost:3306/book_lib?useSSL=false"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: password
amazon:
  accessKey: "AKIAVRUVSN7O6R7B34E2"
  secretKey: "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"
  region: "ap-southeast-1"
  bucket-name: "tuyen-third-bucket"


