jwt:
  signerKey: "d6ad4b004a0e52c86afdc7f283ed735f906736c05d8be178606f62efaabe11007af47f17e1b4c335f51cf52887d6abced19fb16903dadcad6106cda1474bc26a"

server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:auth_lib}?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
#spring:
#  application:
#    name: auth_service
#  datasource:
#
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/auth_lib?useSSL=false}
#    username: root
#    password: 12345678
#    driverClassName: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: password

amazon:
  accessKey: "AKIAVRUVSN7O6R7B34E2"
  secretKey: "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"
  region: "ap-southeast-1"
  bucket-name: "tuyen-third-bucket"


